// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 0.1.3adb7b847c665ef57479d17889c5b121579dbbef 2015-02-12T20:34:45Z

#include "tutorial_About.h"

const char *tutorial_What = "@(#)CCNx 1.0 Tutorial Demo NDS/CCN-Tutorial-Demo.git:de2b26892579dcf6ed6e3029cfe06b9404b7b6b3: 2015-02-12T20:36:20.034592\n@(#)\tCopyright 2014-2015 Palo Alto Research Center (PARC), a Xerox company.\n@(#)\tAll Rights Reserved. Use is subject to license terms.";

const char *
tutorialAbout_Name(void)
{
    return "CCNx 1.0 Tutorial Demo";
}

const char *
tutorialAbout_Version(void)
{
    return "NDS/CCN-Tutorial-Demo.git:de2b26892579dcf6ed6e3029cfe06b9404b7b6b3:";
}

const char *
tutorialAbout_About(void)
{
    return "CCNx 1.0 Tutorial Demo NDS/CCN-Tutorial-Demo.git:de2b26892579dcf6ed6e3029cfe06b9404b7b6b3: 2015-02-12T20:36:20.034592\nCopyright 2014-2015 Palo Alto Research Center (PARC), a Xerox company.\nAll Rights Reserved. Use is subject to license terms.\n";
}

const char *
tutorialAbout_MiniNotice(void)
{
    return "Copyright 2014-2015 Palo Alto Research Center (PARC), a Xerox company.\nAll Rights Reserved. Use is subject to license terms.\n";
}

const char *
tutorialAbout_ShortNotice(void)
{
    return "Copyright 2014-2015 Palo Alto Research Center (PARC), a Xerox company.\nAll Rights Reserved. Use is subject to license terms.\n\nPARC and the PARC Logo are trademarks or registered trademarks of\nPalo Alto Research Center Incorporated, in the U.S. and other countries.\n\nU.S. Government Restricted Rights: Use or reproduction of this Software and\naccompanying documentation are subject to restrictions set forth \nin the Federal Acquisition Regulation and its supplements.\n";
}

const char *
tutorialAbout_LongNotice(void)
{
    return "Copyright 2014-2015 Palo Alto Research Center (PARC), a Xerox company.\n3333 Coyote Hill Road, Palo Alto, CA 94304 USA\nAll Rights Reserved. Use is subject to license terms.\n\nPARC and the PARC Logo are trademarks or registered trademarks of\nPalo Alto Research Center Incorporated, in the U.S. and other countries.\n\nU.S. Government Restricted Rights: Use or reproduction of this Software and\naccompanying documentation are subject to restrictions set forth \nin the Federal Acquisition Regulation and its supplements.\n\nThis Software may be covered and controlled by U.S. Export Control laws and\nmay be subject to the export or import laws in other countries. \nExport or reexport to countries subject to U.S. embargo or to entities identified on\nU.S. export exclusion lists, including, but not limited to, the denied persons\nand specially designated nationals lists is strictly prohibited.\n";
}

