// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20160107.e7511dc010a964ced8f1e029573370af487d7b09 2016-01-19T20:00:29Z

#ifndef tutorial_About_h
#define tutorial_About_h
/**
 * Embedded string containing information for the what(1) command.
 *
 */
extern const char *tutorial_What;

/**
 * Return the name as a C string.
 *
 * @return The name as a C string.
 */
const char *tutorialAbout_Name(void);

/**
 * Return the version as a C string.
 *
 * @return The version as a C string.
 */
const char *tutorialAbout_Version(void);

/**
 * Return the About text as a C string.
 *
 * @return The About text as a C string.
 */
const char *tutorialAbout_About(void);

/**
 * Return the minimum copyright notice as a C string.
 *
 * @return The minimum copyright notice as a C string.
 */
const char *tutorialAbout_MiniNotice(void);

/**
 * Return the short copyright notice as a C string.
 *
 * @return The short copyright notice as a C string.
 */
const char *tutorialAbout_ShortNotice(void);

/**
 * Return the long copyright notice as a C string.
 *
 * @return The long copyright notice as a C string.
 */
const char *tutorialAbout_LongNotice(void);

#endif // tutorial_About_h
